[package]
name = "fdb-gen"
version = "0.1.0"
edition = "2018"
authors = ["fdb-rs Developers"]
description = """
Binding generation helper for FoundationDB
"""
license = "MIT OR Apache-2.0"

[features]
default = []
fdb-6_3 = []

[dependencies]
xml-rs = "0.8.3"
