name: schedule-6_3_24

env:
  image_version: 6_3_24
  image_tag: a941c67da0e8

# We adjust the number of iterations in `schedule.sh` so that the job
# takes approximately 1 hour to finish. Jobs are scheduled at minute
# 30.
on:
  schedule:
    - cron: '30 * * * *'

jobs:
  job-on-schedule:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      -
        name: Pull ghcr.io/fdb-rs/fdb-${{ env.image_version }}:${{ env.image_tag }} container
        run: |
          sudo podman pull ghcr.io/fdb-rs/fdb-${{ env.image_version }}:${{ env.image_tag }}
      -
        name: Start container
        run: |
          sudo podman run --name fdb --volume ${GITHUB_WORKSPACE}:/home/runner/fdb --rm ghcr.io/fdb-rs/fdb-${{ env.image_version }}:${{ env.image_tag }} &
      -
        name: Run 6.3/schedule.sh
        run: |
          sudo podman exec --user runner:docker --workdir /home/runner/fdb/nix/ci --tty fdb nix develop .#schedule-6_3_24 --command ./6.3/schedule.sh
      -
        name: Stop container
        run: |
          sudo podman stop fdb
